#!/bin/bash -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SRC_DIR=$( cd "${DIR}/../src/influxdb" && pwd )

rm -rf ${SRC_DIR}/*

GOPATH=${SRC_DIR} go get github.com/influxdb/influxdb/...

find $SRC_DIR -name ".git" | xargs rm -rf 
find $SRC_DIR -name ".hg" | xargs rm -rf 
