#!/bin/bash

RUN_DIR=/var/vcap/sys/run/influxdb
LOG_DIR=/var/vcap/sys/log/influxdb
PIDFILE=${RUN_DIR}/influxdb.pid
JOB_DIR=/var/vcap/jobs/influxdb
CONFIG_FILE=${JOB_DIR}/config/influxdb_config.toml

STORE_DIR=/var/vcap/store/influxdb

PACKAGE_DIR=/var/vcap/packages/influxdb

wait_pidfile() {
  pidfile=$1
  try_kill=$2
  timeout=${3:-0}
  force=${4:-0}
  countdown=$(( $timeout * 10 ))

  if [ -f "$pidfile" ]; then
    pid=$(head -1 "$pidfile")

    if [ -z "$pid" ]; then
      echo "Unable to get pid from $pidfile"
      exit 1
    fi

    if [ -e /proc/$pid ]; then
      if [ "$try_kill" = "1" ]; then
        echo "Killing $pidfile: $pid "
        kill $pid
      fi
      while [ -e /proc/$pid ]; do
        sleep 0.1
        [ "$countdown" != '0' -a $(( $countdown % 10 )) = '0' ] && echo -n .
        if [ $timeout -gt 0 ]; then
          if [ $countdown -eq 0 ]; then
            if [ "$force" = "1" ]; then
              echo -ne "\nKill timed out, using kill -9 on $pid... "
              kill -9 $pid
              sleep 0.5
            fi
            break
          else
            countdown=$(( $countdown - 1 ))
          fi
        fi
      done
      if [ -e /proc/$pid ]; then
        echo "Timed Out"
      else
        echo "Stopped"
      fi
    else
      echo "Process $pid is not running"
    fi

    rm -f $pidfile
  else
    echo "Pidfile $pidfile doesn't exist"
  fi
}

pid_guard() {
  pidfile=$1
  name=$2

  if [ -f "$pidfile" ]; then
    pid=$(head -1 "$pidfile")

    if [ -n "$pid" ] && [ -e /proc/$pid ]; then
      echo "$name is already running, please stop it first"
      exit 1
    fi

    echo "Removing stale pidfile..."
    rm $pidfile
  fi
}

kill_and_wait() {
  pidfile=$1
  # Monit default timeout for start/stop is 30s
  # Append 'with timeout {n} seconds' to monit start/stop program configs
  timeout=${2:-25}
  force=${3:-1}

  wait_pidfile $pidfile 1 $timeout $force
}

case $1 in

start)

pid_guard $PIDFILE "InfluxDB"

mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR
chown -R vcap:vcap $RUN_DIR $LOG_DIR $STORE_DIR

cd $PACKAGE_DIR

ulimit -n 8192

exec chpst -u vcap:vcap ./influxd -config ${CONFIG_FILE} -pidfile ${PIDFILE} >> ${LOG_DIR}/influxdb.log 2>&1

;;

stop)

kill_and_wait $PIDFILE 120

;;

*)
echo "Usage: ctl {start|stop}" ;;

esac